export const ITEM_IMAGES = {
    "Dawat Special Seekh Kebab": "/images/items/dawat-special-seekh-kebab.jpg",
    "Paneer Tikka": "/images/items/paneer-tikka.jpg",
    "Crispy Prawns": "/images/items/crispy-prawns.jpg",
    "Veg Shammi Kebab": "/images/items/veg-shammi-kebab.jpg",
    "Chicken Malai Tikka": "/images/items/chicken-malai-tikka.jpg",
    "Hara Bhara Kebab": "/images/items/hara-bhara-kebab.jpg",
    "Tandoori Mushroom": "/images/items/tandoori-mushroom.jpg",
    "Amritsari Fish Fry": "/images/items/amritsari-fish-fry.jpg",
    "Chicken 65": "/images/items/chicken-65.jpg",
    "Mutton Galouti Kebab": "/images/items/mutton-galouti-kebab.jpg",
    "Chilli Paneer": "/images/items/chilli-paneer.jpg",
    "Gobi Manchurian": "/images/items/gobi-manchurian.jpg",
    "Dawat Signature Biryani": "/images/items/dawat-signature-biryani.jpg",
    "Butter Chicken": "/images/items/butter-chicken.jpg",
    "Dal Makhani": "/images/items/dal-makhani.jpg",
    "Mutton Rogan Josh": "/images/items/mutton-rogan-josh.jpg",
    "Paneer Butter Masala": "/images/items/paneer-butter-masala.jpg",
    "Hyderabadi Chicken Curry": "/images/items/hyderabadi-chicken-curry.jpg",
    "Palak Paneer": "/images/items/palak-paneer.jpg",
    "Kadhai Chicken": "/images/items/kadhai-chicken.jpg",
    "Malai Kofta": "/images/items/malai-kofta.jpg",
    "Mutton Korma": "/images/items/mutton-korma.jpg",
    "Chicken Tikka Masala": "/images/items/chicken-tikka-masala.jpg",
    "Dal Tadka": "/images/items/dal-tadka.jpg",
    "Fish Curry": "/images/items/fish-curry.jpg",
    "Mix Veg Curry": "/images/items/mix-veg-curry.jpg",
    "Bhindi Masala": "/images/items/bhindi-masala.jpg",
    "Chana Masala": "/images/items/chana-masala.jpg",
    "Chicken Do Pyaza": "/images/items/chicken-do-pyaza.jpg",
    "Veg Dum Biryani": "/images/items/veg-dum-biryani.jpg",
    "Jeera Rice": "/images/items/jeera-rice.jpg",
    "Steamed Basmati Rice": "/images/items/steamed-basmati-rice.jpg",
    "Peas Pulao": "/images/items/peas-pulao.jpg",
    "Garlic Naan": "/images/items/garlic-naan.jpg",
    "Stuffed Paratha": "/images/items/stuffed-paratha.jpg",
    "Roomali Roti": "/images/items/roomali-roti.jpg",
    "Laccha Paratha": "/images/items/laccha-paratha.jpg",
    "Butter Naan": "/images/items/butter-naan.jpg",
    "Plain Naan": "/images/items/plain-naan.jpg",
    "Tandoori Roti": "/images/items/tandoori-roti.jpg",
    "Pudina Paratha": "/images/items/pudina-paratha.jpg",
    "Cheese Naan": "/images/items/cheese-naan.jpg",
    "Keema Naan": "/images/items/keema-naan.jpg",
    "Gulab Jamun": "/images/items/gulab-jamun.jpg",
    "Dawat Firni": "/images/items/dawat-firni.jpg",
    "Gajar Ka Halwa": "/images/items/gajar-ka-halwa.jpg",
    "Kulfi Falooda": "/images/items/kulfi-falooda.jpg",
    "Rasmalai": "/images/items/rasmalai.jpg",
    "Moong Dal Halwa": "/images/items/moong-dal-halwa.jpg",
    "Jalebi with Rabri": "/images/items/jalebi-with-rabri.jpg",
    "Ice Cream Trio": "/images/items/ice-cream-trio.jpg",
    "Dawat Special Lassi": "/images/items/dawat-special-lassi.jpg",
    "Mango Lassi": "/images/items/mango-lassi.jpg",
    "Fresh Watermelon Juice": "/images/items/fresh-watermelon-juice.jpg",
    "Masala Chai": "/images/items/masala-chai.jpg",
    "Filter Coffee": "/images/items/filter-coffee.jpg",
    "Fresh Lime Soda": "/images/items/fresh-lime-soda.jpg",
    "Cold Coffee": "/images/items/cold-coffee.jpg",
    "Mint Mojito": "/images/items/mint-mojito.jpg",
    "Jal Jeera": "/images/items/jal-jeera.jpg",
    "Butter Milk": "/images/items/butter-milk.jpg"
};
